-- V10__create_share_links.sql

CREATE TABLE share_links (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             public_id VARCHAR(32) NOT NULL UNIQUE,
                             version BIGINT NOT NULL DEFAULT 0,
                             token VARCHAR(128) NOT NULL UNIQUE,
                             document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
                             created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                             expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             allow_download BOOLEAN NOT NULL DEFAULT TRUE,
                             download_count INTEGER NOT NULL DEFAULT 0,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             created_by VARCHAR(100),
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                             deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_share_links_token ON share_links(token);
CREATE INDEX idx_share_links_document_id ON share_links(document_id);