-- V11__create_password_reset_tokens.sql

CREATE TABLE password_reset_tokens (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       token VARCHAR(6) NOT NULL,
                                       user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                       expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
                                       attempts INTEGER NOT NULL DEFAULT 0,
                                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                       created_by VARCHAR(100),
                                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                       deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE UNIQUE INDEX uk_password_reset_tokens_user_id ON password_reset_tokens(user_id) WHERE is_deleted = FALSE;