-- V2__create_users_and_roles.sql

-- Table: permissions
CREATE TABLE permissions (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             public_id VARCHAR(32) NOT NULL UNIQUE,
                             version BIGINT NOT NULL DEFAULT 0,
                             name VARCHAR(50) NOT NULL UNIQUE,
                             description VARCHAR(255),
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             created_by VARCHAR(100),
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                             deleted_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_permissions_public_id ON permissions(public_id);

-- Table: roles
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id VARCHAR(32) NOT NULL UNIQUE,
                       version BIGINT NOT NULL DEFAULT 0,
                       name VARCHAR(50) NOT NULL UNIQUE,
                       description VARCHAR(255),
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       created_by VARCHAR(100),
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       deleted_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_roles_public_id ON roles(public_id);

-- Table: users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id VARCHAR(32) NOT NULL UNIQUE,
                       version BIGINT NOT NULL DEFAULT 0,
                       email VARCHAR(150) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       first_name VARCHAR(100),
                       last_name VARCHAR(100),
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       email_verified BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       created_by VARCHAR(100),
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       deleted_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_public_id ON users(public_id);

-- Table: roles_permissions (Join Table)
CREATE TABLE roles_permissions (
                                   role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                                   permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
                                   PRIMARY KEY (role_id, permission_id)
);
-- INDEX SUR FK : Crucial en PostgreSQL pour les JOIN et les DELETE CASCADE
CREATE INDEX idx_roles_permissions_role_id ON roles_permissions(role_id);
CREATE INDEX idx_roles_permissions_permission_id ON roles_permissions(permission_id);

-- Table: users_roles (Join Table)
CREATE TABLE users_roles (
                             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                             role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                             PRIMARY KEY (user_id, role_id)
);
-- INDEX SUR FK : Crucial en PostgreSQL pour les JOIN et les DELETE CASCADE
CREATE INDEX idx_users_roles_user_id ON users_roles(user_id);
CREATE INDEX idx_users_roles_role_id ON users_roles(role_id);