-- V3__create_email_verification_tokens.sql

CREATE TABLE email_verification_tokens (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           token VARCHAR(255) NOT NULL UNIQUE,
                                           user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                           expiry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);