-- V6__create_folders.sql

CREATE TABLE folders (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         public_id VARCHAR(32) NOT NULL UNIQUE,
                         version BIGINT NOT NULL DEFAULT 0,
                         name VARCHAR(255) NOT NULL,
                         owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         parent_id BIGINT REFERENCES folders(id) ON DELETE CASCADE,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                         created_by VARCHAR(100),
                         is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_folders_owner_id ON folders(owner_id);
CREATE INDEX idx_folders_parent_id ON folders(parent_id);

-- Empêche les doublons de noms dans un même dossier parent (hors racine)
CREATE UNIQUE INDEX uk_folders_owner_parent_name
    ON folders(owner_id, parent_id, name)
    WHERE is_deleted = FALSE AND parent_id IS NOT NULL;

-- Index pour accélérer la recherche des dossiers racine (parent_id IS NULL)
CREATE INDEX idx_folders_root ON folders(owner_id) WHERE parent_id IS NULL;