-- V7__create_documents.sql

CREATE TABLE documents (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           public_id VARCHAR(32) NOT NULL UNIQUE,
                           version BIGINT NOT NULL DEFAULT 0,
                           name VARCHAR(255) NOT NULL,
                           original_filename VARCHAR(255) NOT NULL,
                           stored_filename VARCHAR(255) NOT NULL UNIQUE,
                           mime_type VARCHAR(100) NOT NULL,
                           size BIGINT NOT NULL,
                           checksum VARCHAR(64) NOT NULL,
                           status VARCHAR(50) NOT NULL,
                           owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           folder_id BIGINT REFERENCES folders(id) ON DELETE SET NULL,
                           created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                           created_by VARCHAR(100),
                           is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                           deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_documents_owner_id ON documents(owner_id);
CREATE INDEX idx_documents_folder_id ON documents(folder_id);
CREATE INDEX idx_documents_stored_filename ON documents(stored_filename);