-- V8__create_audit_logs.sql

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(32) NOT NULL UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    action VARCHAR(100) NOT NULL,
    user_id BIGINT REFERENCES users(id),
    user_email VARCHAR(150), -- Dénormé pour l'audit si l'utilisateur est supprimé
    resource_type VARCHAR(50),
    resource_id VARCHAR(255),
    ip_address VARCHAR(45), -- Support IPv6
    details JSONB, -- Détails flexibles (commentaires, erreurs, etc.)
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(100),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);