spring:
  application:
    name: DocuSphere
  profiles:
    active: dev

  # JPA & Hibernate
  jpa:
    hibernate:
      # En entreprise, on ne laisse JAMAIS Hibernate modifier le schéma.
      # On utilise Flyway pour les migrations.
      ddl-auto: validate
    open-in-view: false # Désactivé pour éviter les problèmes de performance et les transactions cachées
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20 # Optimisation N+1

  # Migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Upload limits
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2MB # Écrit sur disque après 2MB pour ne pas saturer la RAM

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never # Sécurité : ne jamais exposer la stack trace au client
    include-exception: false
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true

logging:
  level:
    root: INFO
    com.docusphere: DEBUG

# Observability
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  info:
    env:
      enabled: true

info:
  app:
    name: DocuSphere
    description: Professional Document Management Platform
    version: 1.0.0
    developer: Delfred Fossi
    repository: https://github.com/Delfred237/docu-sphere