spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/docusphere
    username: docusphere
    password: password
    driver-class-name: org.postgresql.Driver

  # Configuration SMTP pour Mailpit (Mock)
  mail:
    host: localhost
    port: 1025
    username: noreply@docusphere.com
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  jpa:
    show-sql: true

app:
  security:
    jwt-secret: "docusphere_super_secret_key_for_dev_only_change_in_prod_1234567890"
    jwt-expiration-ms: 900000 # 15 minutes
    refresh-token-expiration-ms: 604800000 # 7 jours

  # Configuration compte admin
  admin:
    email: "admin@docusphere.com"
    password: "Admin123!" # Mot de passe par défaut pour le DEV uniquement
    first-name: "System"
    last-name: "Administrator"

  # Configuration compte admin
  manager:
    email: "manager@docusphere.com"
    password: "Manager123!" # Mot de passe par défaut pour le DEV uniquement
    first-name: "System"
    last-name: "Manager"

  # Configuration du stockage des documents
  storage:
    location: "./storage" # Dossier local pour le dev. En prod, ce sera un volume monté ou /var/lib/docusphere
    allowed-mime-types:
      - "application/pdf"
      - "image/jpg"
      - "image/jpeg"
      - "image/png"
      - "application/vnd.openxmlformats-officedocument.word"
      - "application/msword"
    max-file-size: 52428800 #50 MB

# CORS Configuration (externalisée)
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

logging:
  level:
    com.docusphere: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Affiche les paramètres des requêtes SQL