package com.docusphere.storage;

import java.io.InputStream;

public interface StorageService {

    /**
     * Store a file and return its generated unique filename.
     * @param inputStream The file content
     * @param originalFilename Used only for logging/audit, NEVER for storage path
     * @return The generated unique filename (e.g., UUID + extension)
     */
    String store(InputStream inputStream, String originalFilename);

    /**
     * Load a file as a resource (InputStream).
     * @param filename The unique filename generated by store()
     * @return InputStream of the file
     */
    InputStream load(String filename);

    /**
     * Delete a file from the storage.
     */
    void delete(String filename);
}